language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../All-labs
  - make -j
  - ./Vector/Vector
  - ./VectorTest/VectorTest
notifications:
  email: false
